# This file defines the code generation configuration
# for the build_runner package and its builders.

targets:
  $default:
    builders:
      json_serializable:
        options:
          # Options configure how source code is generated for every
          # `@JsonSerializable`-annotated class in the package.
          #
          # The default value for each option is listed.
          # any_map: false
          # checked: false
          # constructor: ""
          # create_factory: true
          # create_to_json: true
          # disallow_unrecognized_keys: false
          # explicit_to_json: false
          # field_rename: none
          # generic_argument_factories: false
          # ignore_unannotated: false
          # include_if_null: true
          explicit_to_json: true